repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5
    hooks:
      - id: ruff-format
        args: ["--line-length=80"]
      - id: ruff-check
        name: ruff check core
        args: [
          "--select", "F,I,UP"
        ]
      - id: ruff-check
        name: ruff check ann
        exclude: ^tests/
        args: [
          "--select", "ANN"
        ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        exclude: ^tests/
        args: ["--ignore-missing-imports"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
